name: djangoenv
channels:
  - defaults
dependencies:
  - asgiref=3.2.5=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - django=3.0.3=py_0
  - openssl=1.1.1f=he774522_0
  - pip=20.0.2=py38_1
  - python=3.8.2=h5fd99cc_0
  - pytz=2019.3=py_0
  - setuptools=46.1.3=py38_0
  - sqlite=3.31.1=he774522_0
  - sqlparse=0.3.0=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py38_0
  - wincertstore=0.2=py38_0

